spring:
  application:
    name: Api-Gateway

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 
        localhost: http://locathost/8761/eureka